local MODE = MODE

zb = zb or {}
zb.Points = zb.Points or {}

zb.Points.HMCD_COOP_SPAWN = zb.Points.HMCD_COOP_SPAWN or {}
zb.Points.HMCD_COOP_SPAWN.Color = Color(255,255,255)
zb.Points.HMCD_COOP_SPAWN.Name = "HMCD_COOP_SPAWN"

MODE.Maps = {
    ["d1_trainstation_01"] = {PlayerEqipment = "citizen"},
    ["d1_trainstation_02"] = {PlayerEqipment = "citizen"},
    ["d1_trainstation_03"] = {PlayerEqipment = "citizen"},
    ["d1_trainstation_04"] = {PlayerEqipment = "citizen"},
    ["d1_trainstation_05"] = {PlayerEqipment = "citizen"},
    ["d1_trainstation_06"] = {PlayerEqipment = "refugee"},
    ["d1_canals_01"] = {PlayerEqipment = "refugee"},
    ["d1_canals_01a"] = {PlayerEqipment = "refugee"},
    ["d1_canals_02"] = {PlayerEqipment = "refugee"},
    ["d1_canals_03"] = {PlayerEqipment = "refugee"},
    ["d1_canals_05"] = {PlayerEqipment = "refugee"},
    ["d1_canals_06"] = {PlayerEqipment = "refugee"},
    ["d1_canals_07"] = {PlayerEqipment = "refugee"},
    ["d1_canals_08"] = {PlayerEqipment = "refugee"},
    ["d1_canals_09"] = {PlayerEqipment = "refugee"},
    ["d1_canals_10"] = {PlayerEqipment = "refugee"},
    ["d1_canals_11"] = {PlayerEqipment = "refugee"},
    ["d1_canals_12"] = {PlayerEqipment = "refugee"},
    ["d1_canals_13"] = {PlayerEqipment = "refugee"},
    ["d1_eli_01"] = {PlayerEqipment = "refugee"},
    ["d1_town_01"] = {PlayerEqipment = "rebel"},
    ["d1_town_01a"] = {PlayerEqipment = "rebel"},
    ["d1_town_02"] = {PlayerEqipment = "rebel"},
    ["d1_town_02a"] = {PlayerEqipment = "rebel"},
    ["d1_town_03"] = {PlayerEqipment = "rebel"},
    ["d1_town_04"] = {PlayerEqipment = "rebel"},
    ["d1_town_05"] = {PlayerEqipment = "rebel"},
    ["d2_*"] = {PlayerEqipment = "rebel"},
    ["gmhl2_trainstation_01"] = {PlayerEqipment = "citizen"},
    ["gmhl2_trainstation_02"] = {PlayerEqipment = "citizen"},
    ["gmhl2_canals_01"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_02"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_06"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_07"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_08"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_09"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_10"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_11"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_12"] = {PlayerEqipment = "refugee"},
    ["gmhl2_canals_13"] = {PlayerEqipment = "refugee"},
    ["gmhl2_eli_01"] = {PlayerEqipment = "refugee"},
    ["gmhl2_eli_02"] = {PlayerEqipment = "refugee"},
    ["gmhl2_ravenholm"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_01"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_03"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_04"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_05"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_bridge"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_09"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_10"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_11"] = {PlayerEqipment = "rebel"},
    ["gmhl2_coast_12"] = {PlayerEqipment = "rebel"},
    ["gmhl2_prison_part1"] = {PlayerEqipment = "rebel"},
    ["gmhl2_prison_part2"] = {PlayerEqipment = "rebel"},
    ["gmhl2_c17_part1"] = {PlayerEqipment = "rebel"},
    ["gmhl2_c17_part2"] = {PlayerEqipment = "rebel"},
    ["gmhl2_c17_part3"] = {PlayerEqipment = "rebel"},
    ["gmhl2_c17_part4"] = {PlayerEqipment = "rebel"},
    ["gmhl2_c17_part5"] = {PlayerEqipment = "rebel"},
    ["gmhl2_c17_part6"] = {PlayerEqipment = "rebel"},
    ["gmhl2_citadel_p1"] = {PlayerEqipment = "rebel"},
    ["gmhl2_citadel_04"] = {PlayerEqipment = "rebel"},
    ["gmhl2_citadel_05"] = {PlayerEqipment = "rebel"},
    ["gmhl2_breen_01"] = {PlayerEqipment = "rebel"},
    ["gmhl2_lostcoast"] = {PlayerEqipment = "rebel"}
}
